package com.skjanyou.anime.spider.tencent;


import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.util.EntityUtils;
import org.json.JSONArray;

import com.skjanyou.appl.AppUtil.LogUtil;


public class TX_TEST {

	private static LogUtil log = new LogUtil(TX_TEST.class);
	public static void main(String[] args) throws Exception {
		HttpClient httpClient = new DefaultHttpClient();
		HttpGet httpGet = new HttpGet("http://140.143.29.17:2726/getimg?words=ueyJjb21pYyI6eyJpZCI6NTEyNzQyLCJ0aXRsZSI6Ilx1NjU5N1x1N2Y1N1x1NTkyN1x1OTY0NiIsImNvbGxlY3QiOiIxNzEyNDA4IiwiaXNKYXBhbkNvbWljIjpmYWxzZSwiaXNMaWdodE5vdmVsIjpmYWxzZSwiaXNMaWdodENvbWljIjpmYWxzZSwiaXNGaW5pc2giOmZhbHNlLCJpc1JvYXN0YWJsZSI6dHJ1ZSwiZUlkIjoiS2xCUFNrZEFVRkpRQ0FFZkFRUUVBQXdMSEVOZU5BPT0ifSwiY2hhcHRlciI6eyJjaWQiOjMxLCJjVGl0bGUiOiJcdTdiMmMxXHU4YmRkIFx1NTUxMFx1NGUwOVx1N2E3Zlx1OGQ4YSIsImNTZXEiOiIxIiwidmlwU3RhdHVzIjoxLCJwcmV2Q2lkIjowLCJuZXh0Q2lkIjozMiwiYmxhbmtGaXJzdCI6MSwiY2FuUmVhZCI6dHJ1ZX0sInBpY3R1cmUiOlt7InBpZCI6IjE1MDkiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzIsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTk1JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfM2U0ZmIyODcxMmI3ZjZjNDRhMzk2ZDViZjNhNWZhYjRfMTUwOS5vcmkifSx7InBpZCI6IjE1MDgiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTk0JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfYmQzNDBlMjc3ZThkZDdhZDgyMGM3N2JkZDk1YmY2YjFfMTUwOC5vcmkifSx7InBpZCI6IjE1MDciLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTkzJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfNTJhOGQ0MWE2MGM3Y2U2M2M1MzBkOGNmMGI1N2ZjZDBfMTUwNy5vcmkifSx7InBpZCI6IjE1MDYiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTkxJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfODMwZGVhMTZkMjA3OWJkN2QxN2Q5N2EwYjU5YjM5ODBfMTUwNi5vcmkifSx7InBpZCI6IjE1MDUiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTkwJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfOGM2ZDVhMTlkZTFmYWM2Y2JiNGIwN2YwNTllOTcyYTRfMTUwNS5vcmkifSx7InBpZCI6IjE1MDQiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTg5JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfM2YxNDM2NDIwYzc3OGYwNmMwMTA0NThkZmNiZjlhMjlfMTUwNC5vcmkifSx7InBpZCI6IjE1MDMiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMDEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTg4JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfY2NhMDU2MjhmYjMwNmU1Mzc5OTI4YzBlNDBmMjRhY2ZfMTUwMy5vcmkifSx7InBpZCI6IjE1MDIiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTg3JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZDgwOTdkOGI0MDcyNzA1MzMyYmI0OTQ5YmU2ZTE0MjFfMTUwMi5vcmkifSx7InBpZCI6IjE1MDEiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTg1JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfM2E5OGZmYjkwNjdlZWU1ZWRkNTEzYzI3YjczZWM2ZTZfMTUwMS5vcmkifSx7InBpZCI6IjE1MDAiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTg0JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfMzQ0ZWIzZDFlNDQzMDRmYmIyNDIwODRlZTViODBkOGJfMTUwMC5vcmkifSx7InBpZCI6IjE0OTkiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTgzJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZWE5NjkxNWU0ZGQ4OGQxNGIyYjRkODAzZmFlMzdiNGFfMTQ5OS5vcmkifSx7InBpZCI6IjE0OTgiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMDEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTgzJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfMDE0NDNmODA4MGYzZWUyY2IwNWU3NWNkMWFmMjVmZTlfMTQ5OC5vcmkifSx7InBpZCI6IjE0OTciLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMDEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTgyJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZDZhZWMyNGYyNGMxZTIxOGM4NWUyY2JlNDhjMjQ1ZjdfMTQ5Ny5vcmkifSx7InBpZCI6IjE0OTYiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTgxJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfYjYzNTg0MjNlNjJkMTA1M2VjNWEzZDBhN2IxNGRmZDdfMTQ5Ni5vcmkifSx7InBpZCI6IjE0OTUiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTgwJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfODRmMDkzYTE4ZGQwMjBjZDgyYjBiMTU3ZDI3NjYzODBfMTQ5NS5vcmkifSx7InBpZCI6IjE0OTQiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc5JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfMjVlN2ZlYWZjNTMwMWZhNWRhYWEyM2IwODIxYzJlZWVfMTQ5NC5vcmkifSx7InBpZCI6IjE0OTMiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc4JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfOTUzNDdiN2FhOWMzYjI4NmU5MDE3NzFlOGQ0NDE5MzhfMTQ5My5vcmkifSx7InBpZCI6IjE0OTIiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc3JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZGEwOWU5MDI4OWRlNTc4MGMyYzdkYTU5NWM0OTBjMjlfMTQ5Mi5vcmkifSx7InBpZCI6IjE0OTEiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc2JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZmZiYjUyMTFiZjg2Nzg2YWZlNjQ1YWFjNGVkMGVjM2RfMTQ5MS5vcmkifSx7InBpZCI6IjE0OTAiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc1JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZDRkODk2ZTM1MGRmZDJmZGIyN2QyZTFiY2U3NjFiNTJfMTQ5MC5vcmkifSx7InBpZCI6IjE0ODkiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTc0JmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfOGJiMThhYzFlOWZlZWFhOWQxZWRmYjBlNWM1OTE4MGZfMTQ4OS5vcmkifSx7InBpZCI6IjE0ODgiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTczJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfNTFlYWU4OWQ2YmViNmM0NTY2ZjYxOWI1ZGI3YzgzMzBfMTQ4OC5vcmkifSx7InBpZCI6IjE0ODciLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTcyJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfOGVjNTZkNTEwYjJmM2Y1OTBmMzI0YjUyMGEzODE3NzlfMTQ4Ny5vcmkifSx7InBpZCI6IjE0ODYiLCJ3aWR0aCI6ODAwLCJoZWlnaHQiOjExMzEsInVybCI6Imh0dHA6XC9cL2FjLnRjLnFxLmNvbVwvc3RvcmVfZmlsZV9kb3dubG9hZD9idWlkPTE1MDE3JnVpbj0xNDIyMzc1NTcxJmRpcl9wYXRoPVwvJm5hbWU9MjhfMDBfMTlfZTcxZjJiODYzZTA0ZjRiZWE0ODhlZTUyY2NiZjBlYTVfMTQ4Ni5vcmkifSx7InBpZCI6IjYyOTgiLCJ3aWR0aCI6NjAwLCJoZWlnaHQiOjg0OCwidXJsIjoiaHR0cDpcL1wvYWMudGMucXEuY29tXC9zdG9yZV9maWxlX2Rvd25sb2FkP2J1aWQ9MTUwMTcmdWluPTE0MzQ1NDEzMzImZGlyX3BhdGg9XC8mbmFtZT0xN18xOV80Ml8xOWE2ZjBmNmMyODNhZDAyYzFlNGY1M2M2NzBlNDI3YV82Mjk4Lm9yaSJ9XSwiYWRzIjp7InRvcCI6eyJpZCI6IjUxMjc0MiIsInRpdGxlIjoiXHU2NTk3XHU3ZjU3XHU1OTI3XHU5NjQ2XHU1MmE4XHU3NTNiIiwidXJsIjoiaHR0cDpcL1wvYWMucXEuY29tXC9ldmVudFwvdHJhbnNMaW5rXC9kbGRsMjAxOC5odG1sIiwicGljIjoiaHR0cHM6XC9cL21hbmh1YS5xcGljLmNuXC9vcGVyYXRpb25cLzBcLzI0XzE4XzA2Xzc5NWIwMWJiMjMxODRkMDM5ZDYzZmVhYjUyOTUxOTRiXzE1MTY3ODgzODk0NjIuanBnXC8wIiwid2lkdGgiOiI2NTAiLCJoZWlnaHQiOiIxMTAifSwibGVmdCI6W10sImJvdHRvbSI6W119LCJhcnRpc3QiOnsiYXZhdGFyIjoiaHR0cDpcL1wvdGhpcmRxcS5xbG9nby5jblwvZz9iPXNkayZrPUYxdGVoOTdOekhMR0xwS1Y4VG15dEEmcz0xNDAmdD0xNDgzMzgwNTI2IiwibmljayI6Ilx1OThjZVx1NzBhYlx1NTJhOFx1NzUzYiIsInVpbkNyeXB0IjoiU2xCMVl6bHNjbU5zYzNncmFDdG5TRTFvWW0xQ2R6MDkifX0=");
		HttpResponse response  = httpClient.execute(httpGet);
		HttpEntity entity = response.getEntity();
		String html = EntityUtils.toString(entity);
		
		JSONArray jsonArray = new JSONArray(html);
		int len = jsonArray.length();
		for(int i = 0; i < len;i ++){
			String imgString = jsonArray.getString(i);
			System.out.println(imgString);
		}		
		
		
//		Web web = new TX_Web();
//		web.setSpider(new TX_Spider());
//
//		String url1 = "http://ac.qq.com/ComicView/index/id/520942/cid/1";
////		String url2 = "http://ac.qq.com/Comic/comicInfo/id/1013";
//		String url3 = "http://ac.qq.com/ComicView/index/id/1013/cid/42";
////		Page<Object> page = web.getPageContent("");
////		Page<Object> page = web.getPageContent(url1);
//		Anime anime = new Anime("闪灵二人组");
//		List<Page<Anime>> list = web.getPages(anime);
//		for (Page<Anime> page : list) {
//			Anime a = page.getCurrentPageContent();
//			Queue<Chapter> chapterQueue = a.getChapterQueue();
//			for (Chapter chapter : chapterQueue) {
//				Page<Chapter> chapterPage = web.getPageContent(chapter.getUrl());
//				chapter = chapterPage.getCurrentPageContent();
//				chapter.getImgs();
//				System.out.println(chapter);
//			}
////			System.out.println(a);
//		}
//	
//		
		log.info("***********************************");
//		page.nextPage();
//		page.prePage();
//		Object object = page.getCurrentPageContent();
//		System.out.println(object);
//		page.nextPage();
		
//		List<Object> list = page.getContent(1, 420); 
	}

}
